# Generated by Django 5.2.8 on 2025-11-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BerryFlavor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamageClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('formular', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnMethod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveTarget',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_volatile', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageMethod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('effect_entry', models.CharField(blank=True, max_length=1000, null=True)),
                ('effect_entry_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('effect_detail', models.TextField(blank=True, null=True)),
                ('introduced_generation_id', models.ForeignKey(blank=True, db_column='introduced_generation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.generation')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_jp', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('effect_entry', models.TextField(blank=True, null=True)),
                ('effect_entry_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_contact', models.BooleanField(blank=True, null=True)),
                ('crit_rate', models.IntegerField(blank=True, null=True)),
                ('drain', models.IntegerField(blank=True, null=True)),
                ('healing', models.IntegerField(blank=True, null=True)),
                ('min_hits', models.IntegerField(blank=True, null=True)),
                ('max_hits', models.IntegerField(blank=True, null=True)),
                ('introduced_in_generation_id', models.IntegerField(blank=True, null=True)),
                ('damage_class_id', models.ForeignKey(blank=True, db_column='damage_class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.damageclass')),
                ('move_target_id', models.ForeignKey(blank=True, db_column='move_target_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movetarget')),
                ('type_id', models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.type')),
            ],
        ),
        migrations.CreateModel(
            name='MoveFieldCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_condition_id', models.ForeignKey(blank=True, db_column='field_condition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fieldcondition')),
                ('move_id', models.ForeignKey(blank=True, db_column='move_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.move')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('form', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_independent', models.BooleanField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('special_attack', models.IntegerField(blank=True, null=True)),
                ('special_defense', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('base_experience', models.IntegerField(blank=True, null=True)),
                ('capture_rate', models.IntegerField(blank=True, null=True)),
                ('effort_hp', models.IntegerField(blank=True, null=True)),
                ('effort_atk', models.IntegerField(blank=True, null=True)),
                ('effort_def', models.IntegerField(blank=True, null=True)),
                ('effort_spa', models.IntegerField(blank=True, null=True)),
                ('effort_spd', models.IntegerField(blank=True, null=True)),
                ('effort_spe', models.IntegerField(blank=True, null=True)),
                ('is_battle_only', models.BooleanField(blank=True, null=True)),
                ('is_mega', models.BooleanField(blank=True, null=True)),
                ('is_gmax', models.BooleanField(blank=True, null=True)),
                ('is_region_form', models.BooleanField(blank=True, null=True)),
                ('ability1_id', models.ForeignKey(blank=True, db_column='ability1_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability1', to='api.ability')),
                ('ability2_id', models.ForeignKey(blank=True, db_column='ability2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability2', to='api.ability')),
                ('ability_hidden_id', models.ForeignKey(blank=True, db_column='ability_hidden_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_hidden', to='api.ability')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonFormVariation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('form_variation', models.IntegerField(blank=True, null=True)),
                ('form_variation_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('form_variation_name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_default', models.BooleanField(blank=True, null=True)),
                ('introduced_in_version_group_id', models.IntegerField(blank=True, null=True)),
                ('pokemon_id', models.ForeignKey(blank=True, db_column='pokemon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('evolves_from_species_id', models.IntegerField(blank=True, null=True)),
                ('evolution_chain_id', models.IntegerField(blank=True, null=True)),
                ('gender_rate', models.IntegerField(blank=True, null=True)),
                ('base_happiness', models.IntegerField(blank=True, null=True)),
                ('is_baby', models.BooleanField(blank=True, null=True)),
                ('hatch_counter', models.IntegerField(blank=True, null=True)),
                ('growth_rate_id', models.ForeignKey(blank=True, db_column='growth_rate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.growthrate')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_species_id',
            field=models.ForeignKey(blank=True, db_column='pokemon_species_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemonspecies'),
        ),
        migrations.AddField(
            model_name='generation',
            name='main_region_id',
            field=models.ForeignKey(blank=True, db_column='main_region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region'),
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('dislike_berry_flavor_id', models.ForeignKey(blank=True, db_column='dislike_berry_flavor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dislike_berry_flavor', to='api.berryflavor')),
                ('like_berry_flavor_id', models.ForeignKey(blank=True, db_column='like_berry_flavor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_berry_flavor', to='api.berryflavor')),
                ('lower_stat_id', models.ForeignKey(blank=True, db_column='lower_stat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lower_stat', to='api.stat')),
                ('raise_stat_id', models.ForeignKey(blank=True, db_column='raise_stat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raise_stat', to='api.stat')),
            ],
        ),
        migrations.CreateModel(
            name='MoveStatChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_change_rank', models.IntegerField(blank=True, null=True)),
                ('stat_change_rate', models.IntegerField(blank=True, null=True)),
                ('move_id', models.ForeignKey(blank=True, db_column='move_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.move')),
                ('stat_target_id', models.ForeignKey(blank=True, db_column='stat_target_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movetarget')),
                ('stat_id', models.ForeignKey(blank=True, db_column='stat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stat')),
            ],
        ),
        migrations.CreateModel(
            name='MoveStatusCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_condition_chance', models.FloatField(blank=True, null=True)),
                ('move_id', models.ForeignKey(blank=True, db_column='move_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.move')),
                ('status_condition_id', models.ForeignKey(blank=True, db_column='status_condition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscondition')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hex', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_ko', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_holdable', models.BooleanField(blank=True, null=True)),
                ('fling_power', models.IntegerField(blank=True, null=True)),
                ('effect', models.CharField(blank=True, max_length=1000, null=True)),
                ('sprite_id', models.IntegerField(blank=True, null=True)),
                ('item_category_id', models.ForeignKey(blank=True, db_column='item_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemcategory')),
                ('fling_status_condition_id', models.ForeignKey(blank=True, db_column='fling_status_condition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.statuscondition')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type1_id',
            field=models.ForeignKey(blank=True, db_column='type1_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type1', to='api.type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2_id',
            field=models.ForeignKey(blank=True, db_column='type2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type2', to='api.type'),
        ),
        migrations.CreateModel(
            name='MoveUsageMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.ForeignKey(blank=True, db_column='move_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.move')),
                ('move_usage_method_id', models.ForeignKey(blank=True, db_column='move_usage_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usagemethod')),
            ],
        ),
        migrations.CreateModel(
            name='VersionGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.CharField(blank=True, max_length=1000, null=True)),
                ('generation_id', models.ForeignKey(blank=True, db_column='generation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.generation')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_group_id', models.ForeignKey(blank=True, db_column='version_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.versiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('mastery_level', models.IntegerField(blank=True, null=True)),
                ('learn_method_id', models.ForeignKey(blank=True, db_column='learn_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.learnmethod')),
                ('move_id', models.ForeignKey(blank=True, db_column='move_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.move')),
                ('pokemon_id', models.ForeignKey(blank=True, db_column='pokemon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pokemon')),
                ('version_group_id', models.ForeignKey(blank=True, db_column='version_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.versiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='VersionGroupRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('version_group_id', models.ForeignKey(blank=True, db_column='version_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.versiongroup')),
            ],
        ),
    ]
