# Generated by Django 5.2.8 on 2025-11-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('cid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('start', models.CharField(blank=True, max_length=1000, null=True)),
                ('end', models.CharField(blank=True, max_length=1000, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('rankcnt', models.IntegerField(blank=True, null=True)),
                ('rule', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('rst', models.IntegerField(blank=True, null=True)),
                ('ts1', models.IntegerField(blank=True, null=True)),
                ('ts2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
