# Generated by Django 5.2.8 on 2025-11-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='rankcnt',
            new_name='rank_cnt',
        ),
    ]
