# Generated by Django 5.2.8 on 2025-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_rankcnt_match_rank_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='default_img_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='tera_img_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
