# Generated by Django 5.2.8 on 2025-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_type_default_img_url_type_tera_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='default_img_url',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='tera_img_url',
            new_name='tera_icon_url',
        ),
        migrations.AddField(
            model_name='pokemonformvariation',
            name='sprite_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
