# Generated by Django 5.2.8 on 2025-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_default_img_url_type_icon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
