# Generated by Django 5.2.8 on 2025-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pokemon_sprite_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sprite_id',
        ),
        migrations.AddField(
            model_name='item',
            name='sprite_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
