# Generated by Django 5.2.8 on 2025-12-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_item_sprite_id_item_sprite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nature',
            name='sprite_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
