# Generated by Django 5.2.8 on 2026-01-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nature_sprite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name_smogon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
